const styles = {
  container: {
    background: theme => theme.palette.background.white,
    borderBottomColor: theme => theme.palette.accents.orange,
    border: theme => `1px solid ${theme.palette.grey.B200}`,
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    height: "70px",
  },
  vl: {
    borderLeft: theme => `1px solid ${theme.palette.grey.B200}`,
  },
  box: {
    textSmall: {
      fontSize: "0.8em",
      fontWeight: "400",
      color: theme => theme.palette.grey.B500,
    },
    textLarge: {
      fontSize: "1.2rem",
    },
    boxes: {
      left: {
        height: "100%",
        // width: '100%',
        border: "0px",
        borderRadius: "8px 0 0 8px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        color: theme => theme.palette.text.white,
        background: theme => theme.palette.background.black,
        overflow: "hidden",
      },
      right: {
        height: "100%",
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-evenly",
        width: "100%",
        color: theme => theme.palette.text.grey,
      },
      mobile: {
        left: {
          height: "100px",
          width: "100%",
          border: "0px",
          borderRadius: "8px 8px 0 0",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          color: theme => theme.palette.text.white,
          background: theme => theme.palette.background.black,
          nocards: {
            height: "100px",
            width: "100%",
            border: "0px",
            borderRadius: "8px",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            color: theme => theme.palette.text.white,
            background: theme => theme.palette.background.black,
          },
        },
        right: {
          height: "100%",
          display: "flex",
          flexDirection: "row",
          justifyContent: "space-evenly",
          width: "100%",
          color: theme => theme.palette.text.grey,
        },
      },
    },
    left: {
      color: theme => theme.palette.text.white,
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      height: "100%",
      width: "100%",
    },
    right: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      borderLeft: theme => "1px solid" + theme.palette.grey.B400,
    },
    mobile: {
      left: {
        color: theme => theme.palette.text.white,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        height: "100%",
        width: "100%",
      },
      right: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        height: "100%",
        // margin: theme => theme.spacing(2,0),
        border: theme => "1px solid" + theme.palette.grey.B400,
        "&:last-child": {
          borderBottomLeftRadius: "8px",
          borderBottomRightRadius: "8px",
        },
      },
    },
    border: {
      height: "60%",
      border: "1px solid",
      borderColor: "#ccc",
      margin: "auto 0",
    },
    lower: {
      green: {
        fontWeight: "800",
        color: theme => theme.palette.accents.green,
        height: "30px",
      },
      red: {
        fontWeight: "800",
        color: theme => theme.palette.accents.red,
        height: "30px",
      },
      black: {
        fontWeight: "800",
        color: theme => theme.palette.text.black,
        height: "30px",
      },
      white: {
        fontWeight: "800",
        color: theme => theme.palette.text.white,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        height: "30px",
      },
    },
  },
  logo: {
    textAlign: "center",
    marginBottom: theme => theme.spacing(1),
    [theme => theme.breakpoints.up("sm")]: {
      textAlign: "left",
    },
  },
  text: {
    textAlign: "center",
    color: theme => theme.palette.text.black,
    typography: "heading6",
  },
  textLarge: {
    textAlign: "center",
    color: theme => theme.palette.text.black,
    typography: "h4",
    fontWeight: "bold",
    margin: theme => theme.spacing(1),
  },
  links: {
    display: "flex",
    justifyContent: "space-between",
    padding: theme => theme.spacing(4, 0, 0, 0),
    margin: theme => theme.spacing(0, 0, 0, 6),
    maxWidth: "250px",
  },
  sublinks: {
    display: "flex",
    justifyContent: "center",
    padding: theme => theme.spacing(4, 0, 0, 0),
    margin: theme => theme.spacing(0, 6, 0, 6),
  },
  link: {
    color: theme => theme.palette.grey.B200,
    margin: theme => theme.spacing(0, 4, 0, 4),
    "&:hover": {
      borderBottom: "3px solid",
      borderBottomColor: theme => theme.palette.accents.orange,
    },
  },
};

export default styles;
