import FeaturedBg from "assets/images/light_showcase_bg.png";

const style = {
  card: {
    height: "537px",
  },
  cardActionArea: {
    height: "100%",
    position: "relative",
  },
  featuredBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: { xs: 48, md: 72 },
    width: "100%",
    position: "absolute",
    zIndex: 1,
    backgroundImage: `url(${FeaturedBg})`,
    backgroundSize: "cover",
  },
  featuredImageBox: {
    height: { xs: 24, md: 40 },
  },
  featuredImage: { height: "100%" },
  cardContentContainer: { height: "401px" },
  cardContentBox: {
    height: "401px",
    position: "relative",
    bgcolor: "#F7F8FB",
    width: "calc(100% + 48px)",
    mx: -4,
    mt: -4,
    mb: 2,
    top: 0,
  },
  coverImageBox: {
    position: "relative",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  coverImage1: {
    transform: "rotate(5deg)",
    top: 80,
    position: "absolute",
    height: "240px",
    width: "auto",
  },
  coverImage2: {
    transform: "rotate(-5deg)",
    top: 80,
    position: "absolute",
    height: "240px",
    width: "auto",
  },
  coverImage3: {
    top: 80,
    position: "absolute",
    height: "240px",
    width: "auto",
  },
  showcaseActionsBox: {
    borderLeft: "64px solid transparent",
    borderRight: theme => `64px solid ${theme.palette.background.default}`,
    borderBottom: "64px solid transparent",
    height: 0,
    width: 0,
    position: "absolute",
    right: 0,
    top: 16,
    zIndex: 40,
  },
  cardActionsMiddle: {
    height: 114,
    width: "100%",
  },
  cardActionsMiddleBox: { flex: 1 },
  showcaseName: {
    ml: "8px",
    fontWeight: 600,
    fontSize: "24px",
  },
  showcaseNumCards: { ml: 1 },
  linkIconBox: {
    display: "flex",
    alignItems: "center",
    mt: "8px",
  },
  linkIcon: { transform: "rotate(-45deg)" },
  showcaseStats: {
    ml: "8px",
    mb: 1,
  },
  bottomBox: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    mt: 0.5,
  },
  avatarBox: {
    display: "flex",
    justifyContent: "center",
  },
  avatarNotch: {
    position: "relative",
    left: -2,
    top: 0,
    width: "50px",
    height: "50px",
    zIndex: 2,
    borderBottomLeftRadius: "4px",
  },
  avatarImg: {
    position: "absolute",
    overflow: "hidden",
    height: "45px",
    width: "45px",
    objectFit: "cover",
    zIndex: 1,
    margin: "auto",
  },
  userInfoBox: { flex: 1 },
  linkIconBox2: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flex: 1,
  },
  addedDateText: { display: "block" },
};

export default style;
