/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

export enum GradeVendorName {
  BGS = "BGS",
  CSG = "CSG",
  HGA = "HGA",
  PSA = "PSA",
  Raw = "Raw",
  SGC = "SGC",
}

/**
 * Autogenerated input type of AddUserCardDetailToUserCard
 */
export interface AddUserCardDetailToUserCardInput {
  clientMutationId?: string | null;
  userCardId: string;
  userCardDetailId: string;
}

/**
 * Attributes for card filters
 */
export interface CardFilterAttributes {
  year?: number[] | null;
  setName?: string[] | null;
  sportName?: string[] | null;
  grade?: string[] | null;
  playerName?: string[] | null;
  cardStatus?: string[] | null;
  playerId?: string[] | null;
}

/**
 * Autogenerated input type of CreateUserCardImage
 */
export interface CreateUserCardImageInput {
  clientMutationId?: string | null;
  image: any;
  userCardId: string;
  view?: string | null;
}

/**
 * Autogenerated input type of CreateUserCard
 */
export interface CreateUserCardInput {
  clientMutationId?: string | null;
  purchasePrice?: number | null;
  soldAt?: any | null;
  acquiredAt?: any | null;
  checklistNumber?: string | null;
  year?: string | null;
  isOwned?: boolean | null;
  isStaged?: boolean | null;
  manufacturerId?: string | null;
  cardSetId?: string | null;
  cardId?: string | null;
  playerId?: string | null;
  sportId?: string | null;
  grade?: number | null;
  gradeVendorName?: string | null;
}

/**
 * Autogenerated input type of CreateUserCollectionCard
 */
export interface CreateUserCollectionCardInput {
  clientMutationId?: string | null;
  userCardId: string;
  userCollectionId: string;
}

/**
 * Autogenerated input type of CreateUserCollectionFollower
 */
export interface CreateUserCollectionFollowerInput {
  clientMutationId?: string | null;
  userCollectionId: string;
}

/**
 * Autogenerated input type of CreateUserCollection
 */
export interface CreateUserCollectionInput {
  clientMutationId?: string | null;
  name: string;
  description: string;
}

/**
 * Autogenerated input type of CreateUserCollectionView
 */
export interface CreateUserCollectionViewInput {
  clientMutationId?: string | null;
  userCollectionId: string;
}

/**
 * Autogenerated input type of CreateUserFollower
 */
export interface CreateUserFollowerInput {
  clientMutationId?: string | null;
  userId: string;
}

/**
 * Autogenerated input type of CreateUserInterests
 */
export interface CreateUserInterestsInput {
  clientMutationId?: string | null;
  interestIds: string[];
}

/**
 * Autogenerated input type of CreateUserPlayerInterests
 */
export interface CreateUserPlayerInterestsInput {
  clientMutationId?: string | null;
  playerIds: string[];
}

/**
 * Autogenerated input type of CreateWantListCard
 */
export interface CreateWantListCardInput {
  clientMutationId?: string | null;
  cardId: string;
  cardGradeId?: string | null;
  comment?: string | null;
  budgetHigh?: number | null;
  budgetLow?: number | null;
  willTradeFor?: boolean | null;
  willBuy?: boolean | null;
  isHigher?: boolean | null;
}

/**
 * Autogenerated input type of DeleteUserCardImage
 */
export interface DeleteUserCardImageInput {
  clientMutationId?: string | null;
  id: string;
}

/**
 * Autogenerated input type of DeleteUserCard
 */
export interface DeleteUserCardInput {
  clientMutationId?: string | null;
  id: string;
}

/**
 * Autogenerated input type of DeleteUserCards
 */
export interface DeleteUserCardsInput {
  clientMutationId?: string | null;
  ids: string[];
}

/**
 * Autogenerated input type of DeleteUserCollectionCard
 */
export interface DeleteUserCollectionCardInput {
  clientMutationId?: string | null;
  id: string;
}

/**
 * Autogenerated input type of DeleteUserCollectionFollower
 */
export interface DeleteUserCollectionFollowerInput {
  clientMutationId?: string | null;
  userCollectionId: string;
}

/**
 * Autogenerated input type of DeleteUserCollection
 */
export interface DeleteUserCollectionInput {
  clientMutationId?: string | null;
  id: string;
}

/**
 * Autogenerated input type of DeleteUserFollower
 */
export interface DeleteUserFollowerInput {
  clientMutationId?: string | null;
  id: string;
}

/**
 * Autogenerated input type of DeleteWantListCard
 */
export interface DeleteWantListCardInput {
  clientMutationId?: string | null;
  id: string;
}

/**
 * Attributes for pagination
 */
export interface OffsetAttributes {
  limit?: number | null;
  offset?: number | null;
  reverseDirection?: boolean | null;
}

/**
 * Autogenerated input type of RemoveUserCardDetailFromUserCard
 */
export interface RemoveUserCardDetailFromUserCardInput {
  clientMutationId?: string | null;
  userCardId: string;
  userCardDetailId: string;
}

/**
 * Attributes sorting
 */
export interface SortAttributes {
  sortField?: string | null;
  direction?: string | null;
}

/**
 * Autogenerated input type of UpdateUserCard
 */
export interface UpdateUserCardInput {
  clientMutationId?: string | null;
  id: string;
  cardId?: string | null;
  soldAt?: any | null;
  acquiredAt?: any | null;
  checklistNumber?: string | null;
  year?: string | null;
  isOwned?: boolean | null;
  manufacturerId?: string | null;
  cardSetId?: string | null;
  cardGradeId?: string | null;
  playerId?: string | null;
  sportId?: string | null;
  grade?: number | null;
  gradeVendorName?: string | null;
  isStaged?: boolean | null;
  acquisitionSource?: string | null;
  cardStatus?: string | null;
  storageLocation?: string | null;
  editionNumber?: number | null;
  editionSize?: number | null;
  purchasePrice?: number | null;
  gradingCost?: number | null;
  gradeId?: string | null;
  isPublic?: boolean | null;
}

/**
 * Autogenerated input type of UpdateUserCollection
 */
export interface UpdateUserCollectionInput {
  clientMutationId?: string | null;
  id: string;
  name?: string | null;
  description?: string | null;
  isPublic?: boolean | null;
  isFeatured?: boolean | null;
  isVisible?: boolean | null;
}

/**
 * Autogenerated input type of UpdateUserCollections
 */
export interface UpdateUserCollectionsInput {
  clientMutationId?: string | null;
  ids: string[];
  isVisible?: boolean | null;
  isFeatured?: boolean | null;
}

/**
 * Autogenerated input type of UpdateUser
 */
export interface UpdateUserInput {
  clientMutationId?: string | null;
  id: string;
  email?: string | null;
  username?: string | null;
  password?: string | null;
  isOnboarded?: boolean | null;
}

/**
 * Autogenerated input type of UpdateUserProfile
 */
export interface UpdateUserProfileInput {
  clientMutationId?: string | null;
  id: string;
  address1?: string | null;
  address2?: string | null;
  bio?: string | null;
  city?: string | null;
  clubhouseUser?: string | null;
  country?: string | null;
  displayName?: string | null;
  ebayName?: string | null;
  facebookName?: string | null;
  firstName?: string | null;
  instagramUser?: string | null;
  lastName?: string | null;
  location?: string | null;
  myslabsUser?: string | null;
  phoneNumber?: string | null;
  snapchatUser?: string | null;
  starstockUser?: string | null;
  state?: string | null;
  tiktokUser?: string | null;
  twitterUser?: string | null;
  userId?: number | null;
  websiteUrl?: string | null;
  whatnotUser?: string | null;
  youtubeUser?: string | null;
  zip?: string | null;
  experienceLevel?: string | null;
}

/**
 * Autogenerated input type of UpdateWantListCard
 */
export interface UpdateWantListCardInput {
  clientMutationId?: string | null;
  id: string;
  cardId?: string | null;
  cardGradeId?: string | null;
  comment?: string | null;
  budgetHigh?: number | null;
  budgetLow?: number | null;
  willTradeFor?: boolean | null;
  willBuy?: boolean | null;
  isHigher?: boolean | null;
}

/**
 * Autogenerated input type of UserFacebookLogin
 */
export interface UserFacebookLoginInput {
  clientMutationId?: string | null;
  uid: string;
  accessToken: string;
  signedRequest: string;
  email: string;
}

/**
 * Autogenerated input type of UserGoogleLogin
 */
export interface UserGoogleLoginInput {
  clientMutationId?: string | null;
  uid: string;
  email: string;
  firstName: string;
  lastName: string;
  imageUrl?: string | null;
}

//==============================================================
// END Enums and Input Objects
//==============================================================
